# Create Kubernetes secrets for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: streaming-intelligence-secrets
type: Opaque
stringData:
  REDDIT_CLIENT_ID: "GXteM3_oKbVpx8HrWwuC_w"
  REDDIT_CLIENT_SECRET: "d3C5NGCkjS5pNPDts00LHOnGyieiIw"
  REDDIT_USER_AGENT: "streaming-intelligence-bot/1.0"
  SNOWFLAKE_USER: "MCAPPARELLI1"
  SNOWFLAKE_PASSWORD: "Limabellabean55"
  SNOWFLAKE_ACCOUNT: "XKQBOYS-LX35596"
  SNOWFLAKE_WAREHOUSE: "COMPUTE_WH"
  SNOWFLAKE_DATABASE: "STREAMING_INTELLIGENCE"
  SNOWFLAKE_SCHEMA: "RAW_DATA"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-intelligence-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "192.168.1.159:9092"